---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-tls-secret
  namespace: elasticsearch
spec:
  secretName: elastic-tls-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Cluster CA
  commonName: elasticsearch-es-http
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - 'elasticsearch-es-http.elasticsearch.es.local'
    - 'elasticsearch-es-http'
    - 'elasticsearch-es-http.elasticsearch.svc'
    - 'elasticsearch-es-http.elasticsearch'
    - 'elasticsearch-es-internal-http.elasticsearch.svc'
    - 'elasticsearch-es-internal-http.elasticsearch'
    - '*.elasticsearch-es-default.elasticsearch.svc'
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
